/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMerchandiseRouteImport } from './routes/_authenticated/merchandise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompetitionsRouteImport } from './routes/_authenticated/competitions'
import { Route as AuthenticatedCoachesRouteImport } from './routes/_authenticated/coaches'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAthletesIndexRouteImport } from './routes/_authenticated/athletes.index'
import { Route as AuthenticatedBranchesCodeRouteImport } from './routes/_authenticated/branches.$code'
import { Route as AuthenticatedAthletesNewRouteImport } from './routes/_authenticated/athletes.new'
import { Route as AuthenticatedAthletesIdRouteImport } from './routes/_authenticated/athletes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchandiseRoute =
  AuthenticatedMerchandiseRouteImport.update({
    id: '/merchandise',
    path: '/merchandise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitionsRoute =
  AuthenticatedCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachesRoute = AuthenticatedCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthletesIndexRoute =
  AuthenticatedAthletesIndexRouteImport.update({
    id: '/athletes/',
    path: '/athletes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesCodeRoute =
  AuthenticatedBranchesCodeRouteImport.update({
    id: '/$code',
    path: '/$code',
    getParentRoute: () => AuthenticatedBranchesRoute,
  } as any)
const AuthenticatedAthletesNewRoute =
  AuthenticatedAthletesNewRouteImport.update({
    id: '/athletes/new',
    path: '/athletes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthletesIdRoute = AuthenticatedAthletesIdRouteImport.update({
  id: '/athletes/$id',
  path: '/athletes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRouteWithChildren
  '/coaches': typeof AuthenticatedCoachesRoute
  '/competitions': typeof AuthenticatedCompetitionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/merchandise': typeof AuthenticatedMerchandiseRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/athletes/new': typeof AuthenticatedAthletesNewRoute
  '/branches/$code': typeof AuthenticatedBranchesCodeRoute
  '/athletes/': typeof AuthenticatedAthletesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branches': typeof AuthenticatedBranchesRouteWithChildren
  '/coaches': typeof AuthenticatedCoachesRoute
  '/competitions': typeof AuthenticatedCompetitionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/merchandise': typeof AuthenticatedMerchandiseRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/athletes/new': typeof AuthenticatedAthletesNewRoute
  '/branches/$code': typeof AuthenticatedBranchesCodeRoute
  '/athletes': typeof AuthenticatedAthletesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRouteWithChildren
  '/_authenticated/coaches': typeof AuthenticatedCoachesRoute
  '/_authenticated/competitions': typeof AuthenticatedCompetitionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/merchandise': typeof AuthenticatedMerchandiseRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/_authenticated/athletes/new': typeof AuthenticatedAthletesNewRoute
  '/_authenticated/branches/$code': typeof AuthenticatedBranchesCodeRoute
  '/_authenticated/athletes/': typeof AuthenticatedAthletesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/branches'
    | '/coaches'
    | '/competitions'
    | '/dashboard'
    | '/merchandise'
    | '/payments'
    | '/transfers'
    | '/athletes/$id'
    | '/athletes/new'
    | '/branches/$code'
    | '/athletes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/branches'
    | '/coaches'
    | '/competitions'
    | '/dashboard'
    | '/merchandise'
    | '/payments'
    | '/transfers'
    | '/athletes/$id'
    | '/athletes/new'
    | '/branches/$code'
    | '/athletes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/assessments'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/branches'
    | '/_authenticated/coaches'
    | '/_authenticated/competitions'
    | '/_authenticated/dashboard'
    | '/_authenticated/merchandise'
    | '/_authenticated/payments'
    | '/_authenticated/transfers'
    | '/_authenticated/athletes/$id'
    | '/_authenticated/athletes/new'
    | '/_authenticated/branches/$code'
    | '/_authenticated/athletes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchandise': {
      id: '/_authenticated/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof AuthenticatedMerchandiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitions': {
      id: '/_authenticated/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof AuthenticatedCompetitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches': {
      id: '/_authenticated/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof AuthenticatedCoachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletes/': {
      id: '/_authenticated/athletes/'
      path: '/athletes'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AuthenticatedAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/$code': {
      id: '/_authenticated/branches/$code'
      path: '/$code'
      fullPath: '/branches/$code'
      preLoaderRoute: typeof AuthenticatedBranchesCodeRouteImport
      parentRoute: typeof AuthenticatedBranchesRoute
    }
    '/_authenticated/athletes/new': {
      id: '/_authenticated/athletes/new'
      path: '/athletes/new'
      fullPath: '/athletes/new'
      preLoaderRoute: typeof AuthenticatedAthletesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletes/$id': {
      id: '/_authenticated/athletes/$id'
      path: '/athletes/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AuthenticatedAthletesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBranchesRouteChildren {
  AuthenticatedBranchesCodeRoute: typeof AuthenticatedBranchesCodeRoute
}

const AuthenticatedBranchesRouteChildren: AuthenticatedBranchesRouteChildren = {
  AuthenticatedBranchesCodeRoute: AuthenticatedBranchesCodeRoute,
}

const AuthenticatedBranchesRouteWithChildren =
  AuthenticatedBranchesRoute._addFileChildren(
    AuthenticatedBranchesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRouteWithChildren
  AuthenticatedCoachesRoute: typeof AuthenticatedCoachesRoute
  AuthenticatedCompetitionsRoute: typeof AuthenticatedCompetitionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMerchandiseRoute: typeof AuthenticatedMerchandiseRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedAthletesIdRoute: typeof AuthenticatedAthletesIdRoute
  AuthenticatedAthletesNewRoute: typeof AuthenticatedAthletesNewRoute
  AuthenticatedAthletesIndexRoute: typeof AuthenticatedAthletesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRouteWithChildren,
  AuthenticatedCoachesRoute: AuthenticatedCoachesRoute,
  AuthenticatedCompetitionsRoute: AuthenticatedCompetitionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMerchandiseRoute: AuthenticatedMerchandiseRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedAthletesIdRoute: AuthenticatedAthletesIdRoute,
  AuthenticatedAthletesNewRoute: AuthenticatedAthletesNewRoute,
  AuthenticatedAthletesIndexRoute: AuthenticatedAthletesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
